### ISSUE TITLE
Compile on Ubuntu 

### ISSUE THREAD

**Issue by FlintPQ** [fedden/RenderMan#16]
```
flint@flintUbuntuWP:~/RenderMan-master/Builds/LinuxMakefile/build$ python
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librenderman
JUCE v5.2.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_librenderman)
>>> exit()
flint@flintUbuntuWP:~/RenderMan-master/Builds/LinuxMakefile/build$ python2
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import librenderman
JUCE v5.2.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (initlibrenderman)
>>> 
```

That's it. The same problem both on Py2 and Py3

**Comment by c0m0r1** [comment]
I have same problem with this. Even though I confirmed that the initlibrenderman function exists in the librenderman.so file
![image](https://user-images.githubusercontent.com/42940224/81683533-2dee9280-9491-11ea-8451-e4a8f63eff9f.png)

**Comment by orrimoch** [comment]
Any solution for that?

**Comment by doronAtuar** [comment]
Works for me on ubuntu 16.04
But I did have a problem on 18.04

**Comment by fedden** [comment]
Hey all, please accept my apologies for the silence on your problems. This is a project that I wrote whilst at university and I now don't have time to support in a professional capacity, but I appreciate it's a tool that is of use to you. 

I'm wondering if any of you would like to become collaborators so you can put this repository in a state that works for you?

**Comment by orrimoch** [comment]
Thanks!
It works solved using ubuntu 16 docker 👌

**Comment by hichiaty** [comment]
Anyone solved this on ubuntu > 16?

**Comment by turian** [comment]
I was able to solve this on Ubuntu 18.04 by changing the Makefile by changing

```
-fvisibility=hidden
```

to

```
-fvisibility=default
```

You still must load the module using python2.7

I have *not* been successful yet at loading a .so VST
