### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_librenderman)

### ISSUE THREAD

**Issue by drscotthawley** [fedden/RenderMan#7]
Thanks for making this!

I installed boost-python, successfully built the XCode project, renamed the built file to remove the ".dylib", but when I run the "Does It Work?" check, I get...

```
$ python
Python 3.5.3 | packaged by conda-forge | (default, Feb 10 2017, 07:09:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import librenderman as rm
JUCE v5.2.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_librenderman)
>>>
```

Any suggestions on how one might fix this?

In the current directory I have...
```
$ ls
librenderman.so
```

Running Mac OS X 10.13.3 (High Sierra), XCode 9.2, Python 3.5.2 (Anaconda)

**Comment by fedden** [comment]
Hi Scott, thanks for getting in touch! 

Admittedly the repo needs a bit of work and I don't currently have an OSX build system, but I do need to go through this on Linux and have a look at things, as it has been a while since I really evaluated the state of the code. I'll do so later today and get back to you.

**Comment by fedden** [comment]
Okay, so a few things. Firstly _as is_, the repository is only going to support Python 2.7. 

This is because of both the boost python bindings and also the makefile that is generated by JUCE. JUCE is a cross platform framework that allows projects to be managed through something called the Projucer. [If you download the latest version of JUCE](https://juce.com/get-juce) you should be able to manage the RenderMan.jucer file at the root of the repository. The JUCE project also makes use of the Boost library, to make python bindings to the C++ functions [defined here.](https://github.com/fedden/RenderMan/blob/master/Source/source.cpp) The .jucer file links to the Boost headers that are installed onto your system in the installation process. 

I think really it is time to move everything to Python 3, as well as to massively simplify the installation process. I'm admittedly unsure of the correct way at this point. My todo list is essentially:
1. Figure out a way to author the .jucer file so arguments could be sent to the respective makefile to allow the user to select Python2 / Python3
2. Create an easy install method via pip or some other method.

With respect to your problem it's very hard for me to advise as I do not have a working OSX system. I am here to help however. Here is what I did on Ubuntu 16.04. The steps wont be the same, some paths and environment variables may be different, but the process should be similar.

* You are going to need to remove boost from your system. 
* You will need to then download the source for Boost under current release at http://www.boost.org/
* You will then need cd into the boost source and compile it for python3. I am assuming you are using Python3.5. This is done by running:
```bash
# Run bootstrap with correct flag.
./bootstrap.sh --with-python=python3.5 
# Compile Boost locally.
./b2
# Install Boost system wide.
sudo ./b2 install
```
* Once Boost is installed with Python3 bindings, you'll need to fire up the Projucer and edit the RenderMan.jucer file. 
* On the left-hand side of the Projucer window, open up the Exporters dropdown. As a Mac user, you'll be interested in the Xcode exporter. 
* Press the 'Xcode (MacOSX) drop-down and you'll see some options for 'Extra Linker Flags'. Edit the flags accordingly:
```bash
# Change this.
-shared -lpython2.7 -lboost_python
# To this.
-shared -lpython3.5m -lboost_python-py35
```
* Then go to the Debug and Release settings for the Xcode exporter (under the drop-down you initially clicked). For both Debug and Release, under header search paths, change `/usr/include/python2.7` to  
`/usr/include/python3.5`.
* Save the projucer. It will now create a new Xcode project. 
* Opening the Xcode project, clean and build. 
* Let me know the output!

**Comment by harritaylor** [comment]
I tried your solution @fedden but ran into a few issues. I am using MacOS 10.13 and Python 3.6 *installed via Homebrew*. I did eventually get it working by following the following steps (All commands are given for my exact installation, so some modification of commands may be required):

On terminal:
1. Remove boost-python and install the equivalent library for python3:

```zsh
brew remove boost-python && brew install boost-python3
```

2. Provided that python3 is installed via Homebrew, add a [symlink](https://kb.iu.edu/d/abbe) to `/usr/local/include` pointing to the python3.x headers that Brew has installed. In my case:

```zsh
sudo ln -s /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/include/python3.6m /usr/local/include/python3.6
```

3. Add a symlink for the boost library:

```zsh
sudo ln -s /usr/local/Cellar/boost/1.66.0/include/boost /usr/local/include/boost
```

4. Add a symlink for the python3.x library that Brew has installed inside the `/usr/local/lib` folder. Cannot add directly as "python3.x" is being used for site-packages. There is probably a more elegant solution but this is what I came up with: 

```zsh
sudo ln -s /usr/local/Cellar/python3/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib /usr/local/lib/python3.6/lib
```

Now, inside Projucer:
5. Set the "Extra Linker Flags" in Exporters → Xcode(MacOS) to:
``` 
-shared -lpython3.6m -lboost_python3
```

6. In both Exporters → Xcode(MacOS) → debug & Exporters → Xcode(MacOS) → release set:
6.1 "header search paths":
``` 
/usr/local/include
/usr/local/include/python3.6
```

6.2 "Extra library search paths":
```
/usr/local/include
/usr/local/include/python3.6
```

Hit save in Projucer, and then Build inside Xcode (⌘B), and *hopefully* the build will succeed. If not, clean (⌘⇧K) and build again. This is the most system-independent solution I could come up with so far.

**Comment by drscotthawley** [comment]
@harritaylor @fedden Sorry for the delay, I've been out of it for a bit.  I will gladly try out @harritaylor's patch! :-)

**Comment by drscotthawley** [comment]
I ran into problems trying this on both Linux and Mac.  I pulled the latest RenderMan, and then....

**Linux:**
I built the library, and after fighting errors involving Anaconda's libstdc++.so.6 vs. the system's version of same (hint: [solution here](https://stackoverflow.com/questions/39844772/cxxabi-1-3-8-not-found-in-tensorflow-gpu-install-from-source)), I now, with the updated-and-merged-for-Python3 version of RenderMan, get...


```
>>> import librenderman as rm
JUCE v5.2.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_librenderman)
```
i.e., exactly the same error as in the title of this Issue.

So... when you say "I have got RenderMan working in Python3 on Linux", what did you do?   Do I perhaps need to pull code from a different branch?

----


**Mac:**
Loading @harritaylor 's RenderMan-py36.jucer file, and exporting to Xcode, the Xcode build fails with the error
```
ld: library not found for -lboost_python3
```
...Turns out it's because brew doesn't install any "libboost_python3" files, it installs them as "libboost_python36".  At least for the new version of boost_python3 (1.67).  Ok, so we can fix that:
```
$ cd /usr/local/lib; ln -s libboost_python36.dylib libboost_python3.dylib
```
...Xcode build succeeded!  
```
$ cd ~/Downloads/RenderMan/Builds/MacOSX/build/Debug
$ ls
librenderman.so.dylib
$ mv librenderman.so.dylib librenderman.so
```
Divest myself of Anaconda environment via `$ source deactivate` and then

```
$ which python3.6
/usr/local/bin/python3.6
$ python
Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import librenderman as rm
JUCE v5.2.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (initlibrenderman)
```

Ok...I'm confused. This again seems like a Python 3 code issue, not an OS issue.

**Comment by harritaylor** [comment]
@drscotthawley For the Mac example, you are running Python 2

>`$ python`
>`$ Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) `

Please try running the command with python3 to start your REPL with python3.6, and see if there still is an issue.

Also, side note: I got it running on linux by modifying the makefile and replacing "python2.6" and "boost_python" with "python3.6m" and "boost_python3" respectively, then making the file. A change in the version numbers may be needed for your platform though. I remember it took a bit of fiddling around.

**Comment by drscotthawley** [comment]
@harritaylor Right, I noticed that error and already went back to delete most of my post, to say that I got it working once I used the correct python!    
I'll try the makefile changes you suggest for Linux, thanks!

**Comment by harritaylor** [comment]
@drscotthawley Great! Easy mistake. Looking forward to not having to deal with 2 different versions of python soon :-). 
Let me know if you still have issues with the Linux version.

**Comment by drscotthawley** [comment]
Just as a follow-up: Whether on Linux or Mac, to get it to work with Anaconda python, you just need to give the build system the locations of the Anaconda libraries.  

So, on Mac, in the Projucer, in Exporters > Xcode(Mac), I have the following lines:

*Header search paths:*
/usr/local/include
/Users/shawley/anaconda/envs/py36/include
/Users/shawley/anaconda/pkgs/python-3.6.0-2/include/python3.6m/

*Extra library search paths:*
/usr/local/lib
/Users/shawley/anaconda/envs/py36/lib

**Comment by fedden** [comment]
Great thanks for this - I'll make sure this is all automated in the coming months :)

**Comment by jwignall** [comment]
Hi there,  

I realise the previous comments were added nearly a year ago, but I am trying to use this library and I had the same Module Import error on Ubuntu. I tried to edit the makefile, but cannot get it to compile. Can someone explain which lines I need to edit? I tried: 

- Changing -I/usr/include/python2.7 to -I/usr/include/python3.5 (I'm running Python 3.5.2)
- Changing -lpython2.7 -lboost_python to -lpython3 -lboost_python3.5 or -lpython3 -lboost_python3.5, lpython3 -lboost_python-py35 etc.

I still get errors about not finding -lpython and lboost_python3 etc. 

Thanks in advance! I am relatively new to Linux and haven't needed to do this before!
Jake

**Comment by harritaylor** [comment]
Hi Jake,

I’m away from my Ubuntu machine at the moment, however I’d recommend trying the following steps as you’re installing for python 3.

1. Install the JUCE app from roli
2. Open the RenderMan-py36.jucer<https://github.com/fedden/RenderMan/blob/master/RenderMan-py36.jucer> file
3. Export the required makefile from within the Projucer app

Then this should produce the correct binary for your system. If not, let me know and I’ll have a proper look tomorrow for you.

Cheers,
Harri

On 18 Feb 2019, at 18:51, jwignall <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

I realise the previous comments were added nearly a year ago, but I am trying to use this library and I had the same Module Import error on Ubuntu. I tried to edit the makefile, but cannot get it to compile. Can someone explain which lines I need to edit? I tried:

  *   Changing -I/usr/include/python2.7 to -I/usr/include/python3.5 (I'm running Python 3.5.2)
  *   Changing -lpython2.7 -lboost_python to -lpython3 -lboost_python3.5 or -lpython3 -lboost_python3.5, lpython3 -lboost_python-py35 etc.

I still get errors about not finding -lpython and lboost_python3 etc.

Thanks in advance! I am relatively new to Linux and haven't needed to do this before!
Jake

**Comment by jwignall** [comment]
Hi Harri,

Unfortunately this still doesn't work. I followed all three steps, but
still get the ImportError when attempting to import the module.

I noticed that the header search path in the Projucer app for this is still
Python2.7, However, changing to Python3.5 I get the following error:
[*path*]/librenderman.so:
undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

Any idea how to solve that?

Thanks in advance, I appreciate your time and efforts!

Thanks,
Jake
